# Generated by Django 6.0.3 on 2026-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MATCH', 'Match Report'), ('ACADEMY', 'Academy'), ('CLUB', 'Club News')], default='CLUB', max_length=20)),
                ('image', models.ImageField(upload_to='news/')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Latest News',
                'ordering': ['-date_posted'],
            },
        ),
    ]
