# Generated by Django 6.0.3 on 2026-03-18 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date'], 'verbose_name_plural': 'Latest News'},
        ),
        migrations.AddField(
            model_name='news',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Manually click 'Today' and 'Now' when making major edits to push to the top."),
        ),
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Select a past date to backdate, or a future date to schedule.'),
        ),
    ]
