# Generated by Django 6.0.3 on 2026-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('Match Day', 'Match Day'), ('Practice', 'Practice'), ('Behind The Scenes', 'Behind The Scenes')], default='Match Day', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this album from the website'),
        ),
    ]
