# Generated by Django 6.0.3 on 2026-03-20 10:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_category_album_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WebP', keep_meta=True, null=True, quality=75, scale=None, size=[800, 500], upload_to='gallery/covers/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=None, size=[1200, None], upload_to='gallery/photos/'),
        ),
    ]
