# Generated by Django 6.0.3 on 2026-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Bengal United', max_length=200)),
                ('history', models.TextField(help_text='The founding story and history of the club.')),
                ('mission', models.TextField(help_text="What is the club's main goal?")),
                ('vision', models.TextField(blank=True, help_text='Where is the club going in the future?', null=True)),
                ('image', models.ImageField(help_text='Cover image for the About section', upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
