# Generated by Django 6.0.3 on 2026-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., High-Performance Gym, Main Pitch', max_length=150)),
                ('description', models.TextField(help_text='Details about the equipment, size, or usage.')),
                ('image', models.ImageField(help_text='A high-quality photo of the facility.', upload_to='facilities/')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
