# Generated by Django 6.0.3 on 2026-03-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Elite Youth Academy, Summer Camp', max_length=200)),
                ('description', models.TextField(help_text='Details about what the program offers.')),
                ('image', models.ImageField(help_text='Upload an action shot for this program', upload_to='programs/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this from the website')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
