# Generated by Django 6.0.3 on 2026-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='JOIN THE NEXT GENERATION OF CHAMPIONS', max_length=200)),
                ('description', models.TextField(default='Spots for our upcoming elite trials are strictly limited. Secure your place now and start your journey.')),
                ('button_text', models.CharField(default='MESSAGE US ON WHATSAPP', max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Upload a cool background photo (Optional)', null=True, upload_to='join_bg/')),
            ],
            options={
                'verbose_name': 'Join Section',
                'verbose_name_plural': 'Join Section',
            },
        ),
    ]
