# Generated by Django 6.0.3 on 2026-03-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_joinsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinsection',
            options={'verbose_name': 'Join Section Settings', 'verbose_name_plural': 'Join Section Settings'},
        ),
        migrations.RemoveField(
            model_name='joinsection',
            name='background_image',
        ),
        migrations.CreateModel(
            name='JoinSectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload photos for the background slider', upload_to='join_section_slider/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which photos appear')),
                ('join_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.joinsection')),
            ],
            options={
                'verbose_name': 'Join Section Background Photo',
                'verbose_name_plural': 'Join Section Background Photos',
                'ordering': ['order'],
            },
        ),
    ]
