# Generated by Django 6.0.3 on 2026-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'ordering': ['-year'], 'verbose_name_plural': 'Trophies'},
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='title',
        ),
        migrations.AddField(
            model_name='trophy',
            name='description',
            field=models.TextField(blank=True, help_text='Short detail about the victory.'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='name',
            field=models.CharField(default='Unknown Trophy', help_text='e.g., Bengal State League', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trophy',
            name='image',
            field=models.ImageField(help_text='Upload a picture of the cup/shield', upload_to='trophies/'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='year',
            field=models.CharField(help_text='e.g., 2024', max_length=4),
        ),
    ]
