# Generated by Django 6.0.3 on 2026-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='e.g., Forward, Midfielder, Defender, Goalkeeper', max_length=50)),
                ('jersey_number', models.PositiveIntegerField()),
                ('photo', models.ImageField(help_text='Upload a transparent PNG or high-quality photo', upload_to='players/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide player from the website')),
            ],
            options={
                'verbose_name_plural': 'First Team Players',
                'ordering': ['jersey_number'],
            },
        ),
    ]
